name: Update Org Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  update-org-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure profile directory exists
        run: mkdir -p ../profile

      - name: Fetch Organization Stats
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: |
          ORG_NAME="JM-n-Co"

          # Fetch Total Repositories
          REPO_COUNT=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/orgs/$ORG_NAME/repos" | jq length)

          # Fetch Total Members
          MEMBER_COUNT=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/orgs/$ORG_NAME/members" | jq length)

          # Fetch Total Commits
          COMMIT_COUNT=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/search/commits?q=org:$ORG_NAME" -H "Accept: application/vnd.github.cloak-preview" | jq .total_count)

          echo "ORG_REPOS=$REPO_COUNT" >> $GITHUB_ENV
          echo "ORG_MEMBERS=$MEMBER_COUNT" >> $GITHUB_ENV
          echo "ORG_COMMITS=$COMMIT_COUNT" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          cat <<EOF > ../profile/README.md
          # 📊 Organization Statistics

          | Metric            | Count |
          |------------------|------|
          | 📂 Total Repositories | $ORG_REPOS |
          | 🔥 Total Commits   | $ORG_COMMITS |
          | 👥 Total Members   | $ORG_MEMBERS |

          EOF

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add ../profile/README.md
          git commit -m "Update organization statistics [bot]" || echo "No changes to commit"
          git push
