name: Update Org Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  update-org-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure profile directory exists
        run: mkdir -p profile

      - name: Authenticate GitHub CLI
        run: echo ${{ secrets.GH_API_TOKEN }} | gh auth login --with-token

      - name: Fetch Organization Stats (Using `gh`)
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_API_TOKEN }}
        run: |
          ORG_NAME="JM-n-Co"

          # Fetch Total Repositories
          REPO_COUNT=$(gh repo list $ORG_NAME --limit 100 --json name --jq 'length')

          # Fetch Total Members
          MEMBER_COUNT=$(gh api orgs/$ORG_NAME/members --jq 'length')

          # Fetch Total Commits (Alternative approach using `gh`)
          COMMIT_COUNT=$(gh search commits --owner $ORG_NAME --json totalCount --jq '.totalCount')

          # Handle null commits issue (default to 0 if null)
          if [ -z "$COMMIT_COUNT" ] || [ "$COMMIT_COUNT" = "null" ]; then
            COMMIT_COUNT=0
          fi

          echo "ORG_REPOS=$REPO_COUNT" >> $GITHUB_ENV
          echo "ORG_MEMBERS=$MEMBER_COUNT" >> $GITHUB_ENV
          echo "ORG_COMMITS=$COMMIT_COUNT" >> $GITHUB_ENV

      - name: Update Organization README.md
        run: |
          cat <<EOF > profile/README.md
          # 📊 Dev. Jack Statistics

          | Metric            | Count |
          |------------------|------|
          | 📂 Total Repositories | $ORG_REPOS |
          | 🔥 Total Commits   | $ORG_COMMITS |
          | 👥 Total Members   | $ORG_MEMBERS |

          EOF

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add profile/README.md
          git commit -m "Update organization statistics [bot]" || echo "No changes to commit"
          git push
